StarCoreSE/SCModRepository-Dev

- Gamemode Mods/Development/Starcore_Pointslist-Dev/Data/Scripts/Additions/PointAdditions.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/380mm MLE 1935.cs
Tirpitz BP: 250 - 400
Fletcher/Benson BP: 175 - 220
> Point changes to fletcher

- Gamemode Mods/Development/Starcore_Sharetrack-Dev/Data/Scripts/ShipPoints/ShipTracker.cs
- First, the mod needs to be uploaded ingame once so a steamworkshop link is set.
- Then add https://steamcommunity.com/id/starcoretv/  as a friend and contributor to the mod. 
- Create a [Mod Name].yml file, and place it in your local repository's ``.github/workflows``  folder.
- Copy the template from here.
https://github.com/StarCoreSE/SCModRepository/blob/main/.github/SAMPLE-Upload.yml
- Fill out the following fields with your mod's details:
- List changes made.
> added break;

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/SOL_CubeBlocks.sbc
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret_Ammo.cs
Concussion Bolt is less cancerous:
* Push bubble is now really small and easily pushed through
* Homes :^)
* Velocity decreased to 600m/s
* Lowered base damage but increased damage depth NanoDart, now goes 2.5km/s
> Nariman Ammo

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Flechette_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Flechette_Shotgun.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret_Ammo.cs
Various improvements to Nariman and Flechette Shotgun
> Nariman and Flechette Shotgun Improvements

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Flechette_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Flechette_Shotgun.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Goncol_Animation.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Goncol_Generator.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Heavy_MAC.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Heavy_MAC_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret_Ammo.cs
Nariman:
* Disabled EWAR
* Lowered brightness significantly
* Lowered AMS damage
Hercules:
* Increased reload time from 2->10sec
* Trail now gold/yellow
Goncol:
* Extended visibility from 1->10km, maybe
Flechette Shotgun:
* Basic shell now Buckshot ammo
* New ammo, Smart Flak, purple flak that homes in on projectiles and targets
> Major Rework

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/150mm Twin Var.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/150mm Twin.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508HE.cs
Changelog:
Elbing reload: 500 - 250
Thunderer HE:
Fragment damage: 1000 - 5000 (should now be doing half of what it was before i hyper nerfed it)
> quick changes

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/SOL_CubeBlocks.sbc
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Flechette_Shotgun.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/ImpulseTorch.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/ImpulseTorchAmmo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Torch_Ammo.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/150mm Twin Var.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/150mm Twin.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508HE.cs
Torch Update
* Removed Restrictions for most guns, except the Saber
* Impulse Torch now functional, at 175bp
* [SOL] has been added to all weapons, not blastplates
> Torch Update

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Torch_Ammo.cs
Should not be out-dps'ing the saber
BaseDamage: 24000->6000f
> Torch Damage Nerf

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InSemiGuideTorp.cs
FUCK IT TORPS ARE FULLY GUIDED BUT STILL SLOW
> fuck it guidance torps

- Gamemode Mods/Development/Starcore_Pointslist-Dev/Data/Scripts/Additions/PointAdditions.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/380mm MLE 1935.cs
Today i will actually listen to the people who use them, and not the piece of paper called the dossier
> Reverting things

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508mm.cs
FUCKING FIX THUNDERER HAVING 70K RANGE IT SHOOULD BE 7K FUCKING REEEEE
> I PUT A FUCKING EXTRA 0 IN IT REEEEE

- Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev/Data/CubeBlocks_SA_HMI.sbc
- Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev/Data/Scripts/CoreParts/CerberusAmmo.cs
- Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev/Data/Scripts/CoreParts/Cerberus_Main.cs
- Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev/Data/Scripts/CoreParts/Cerberus_SecondaryA.cs
- Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev/Data/Scripts/CoreParts/Cerberus_SecondaryB.cs
- Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev/Data/Scripts/CoreParts/Silvius.cs
- Weapon Mods/Development/Starcore_Serpent_Arms_Heavy_Metal-Dev/Data/Scripts/CoreParts/Silvius_Ammo.cs
- Silvius & Cerberus
> Adjust shot deviation & reload
> Actually made it so the weapon can overheat
> Nerfs to Armor, NonArmor & Shield Damage
> Fixed Shield Bypass
> Slowed down the bullet
> Silvius/Cerberus - 4.3 Nut Tap

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/ArcStrike_Launcher.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/ArcStrike_Launcher_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Flechette_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Small_Chem_Armored_Laser.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Small_Chem_Laser.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Small_Chem_Laser_Ammo.cs
ArcStrike: visual MaxDistance 1km->10km
Shotgun: Buckshot BaseDamage 10-4000f / Smart Flak BaseDamage 40->3000f
-Saber-
* Reworked the heat, mag, and reload to have 5 shots of 5 seconds each, though at reduced damage capacity
* BaseDamage 36000->12000f
* NonArmor modifier 1->0.15f
* Shield modifer 1.5->0.25f
> Last Nights Balances

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Small_Chem_Armored_Laser.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Small_Chem_Laser.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Small_Chem_Laser_Ammo.cs
Nariman: Concussion ammo now has actual aoe
Saber: Pulses now only 2 seconds an use magazine size instead of heat
> Tweakerman

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508AP.cs
> Brotato nerf

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508mm.cs
Now is actually able to hit shit again
> revert deviation on thunderer

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/SOL_CubeBlocks.sbc
Descriptions are accurate once more
> Descriptions make sense

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/BlockCategories.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508mm.cs
Apparently missed the accuracy buff to Thundere REEE,
> Tait dev platform

- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Carronade/LBX5.cs
- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Large SnubFighters/HeavyFighterBay.cs
- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Rockets and Torpedoes/BonfireMissileLauncher.cs
lb5x, fighter, bonfire
- First, the mod needs to be uploaded ingame once so a steamworkshop link is set.
- Then add https://steamcommunity.com/id/starcoretv/  as a friend and contributor to the mod. 
- Create a [Mod Name].yml file, and place it in your local repository's ``.github/workflows``  folder.
- Copy the template from here.
https://github.com/StarCoreSE/SCModRepository/blob/main/.github/SAMPLE-Upload.yml
- Fill out the following fields with your mod's details:
- List changes made.
> adjusting turret limits

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/150mm Type 2 Single.cs
Muzzle on barrel end not inside block
FIXED
> Fix scharnhorst muzzle

- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Particle_Projectiles.sbc
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/ArcStrike_Launcher_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Flechette_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Heavy_MAC.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Heavy_MAC_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/ImpulseTorchAmmo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/Nariman_Turret_Ammo.cs
- Weapon Mods/Development/Anomaly_Solaris_Hypernautics-Dev/Data/Scripts/CoreParts/SA_GaussAP_Animations.cs
> First round of balance passes

- Gamemode Mods/Development/Starcore_Pointslist-Dev/Data/Scripts/Additions/PointAdditions.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/105mmTwin.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/150mmcasematesingle.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/150mmcasematetwin.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/203Quad.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/203Twin.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/BarbetteSet.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/Mk25 Rangefinder.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/PomPomMain.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/105mm SAP.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm Mark 12.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm Mark 24.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm Mark 32.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm SAP Shell.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm Shell.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/150mmHE.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/152mmAP.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InSemiGuideTorp.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InchQuinTorpLaunch.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25inchTorpTwinFixed.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/380mm AP Shell.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/380mm HE Shell.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508AP.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/508HE.cs
Syncing live to dev so they share the same baseline, lets crack some heads
> Sync live branch to dev branch

- Gamemode Mods/Development/Starcore_Sharetrack-Dev/Data/Scripts/ShipPoints/HudPointsList.cs
> fix for incorrect shield number reporting; add a performance timer, get rid of pr template

- Gamemode Mods/Development/Starcore_Sharetrack-Dev/Data/Scripts/ShipPoints/HudPointsList.cs
- Gamemode Mods/Development/Starcore_Sharetrack-Dev/concat_recursive.bat
> decrease load by 14x when shift t'ing a nontracked entity + performance profiler

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Audio.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/406mmAlt.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/CubeBlocks/508mm twin.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Cubeblocks.sbc
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/150mmHE.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InSemiGuideTorp.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InchQuinTorpLaunch.cs
> Tirpitz 5x5 fix*

- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Carronade/LBX5.cs
- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Carronade/LBX_ammo.cs
- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Plasma Weapons/Magnus_Ammotypes.cs
- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Plasma Weapons/Magnus_WeaponParts.cs
- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Rockets and Torpedoes/FixedgunRLXammo.cs
shieldmod 6x -> 4x (since nate said it was balacned around the 0.6x shieldmod that ended up giving infinite regen)
> Rl10x thagaomizer proportional damage reduction + bring latest TIO to dev 

- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Carronade/LBX5.cs
> lbx grid limit 1 dev

- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Rockets and Torpedoes/BonfireMissileAmmo.cs
They should of been feasting against unshielded grids, why weren't they feasting?! Poor preformance on damage graphs, reverting some of the older nerfs they got. Restored (read, enlarged) aoe size and component Modifier set from 0.2 -> 0.3.
> Buff BonfireMissileAmmo.cs

- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Rockets and Torpedoes/SpitfireRocketAmmo.cs
Comp mod 0.3-> 0.4
Aoe per block(w/ linear falloff): 8000->9000
> Buff SpitfireRocketAmmo.cs

- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Carronade/QuadCarronadeAmmo.cs
Made it splash a little more and punch a little less.
Main nerf is 20% reduction in velocity. Velocity: 1250 ->1000 m/s
> Nerf QuadCarronadeAmmo.cs, Shipwreck

- Weapon Mods/Development/TIOStarcore-Dev/Data/Scripts/CoreParts/Plasma Weapons/X-4PlasAmmo.cs
Reduced shrapnel count per bullet from 9 to 7.
Removed shrapnel light armor bullying aoe.
Made sure that shrapnel still does 50% damage to a heavy armor block.
> Significant X4 nerf. Updated Ammo.cs

- Weapon Mods/Development/Heavy-Assault-Systems-Dev/Data/Scripts/CoreParts/Vulcan.cs
> Observe as I change 1 value to significantly buff the vulcan 🖖

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/105mm Twin.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm Mark 12.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm Mark 24.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/127mm Mark 32.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InSemiGuideTorp.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InchQuinTorpLaunch.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/40mm Ammo.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/40mmBoforQuad.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/40mmBoforSingle.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/40mmBoforTwin.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/40mmFlak.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/40mmFlakGun.cs
push to dev + previouis changes
> Lets see if i can debug this network shit on dev

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/105mm SAP.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/105mm Twin.cs
lets see whats causing this performance thing....
> Okay, dev tester

- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/25InSemiGuideTorp.cs
- Weapon Mods/Development/TaitMod_Fletcher_Dev/Data/Scripts/CoreParts/40mmFlak.cs
Torpedos can now be Pd'd thanks to stages, and the 40mm flak now has 36 fragments instead of 360 and are summoning beams i hope
> Torps pd now flak change
